version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-1
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./dockerProjects/mysql-1/volumes/var/lib/mysql:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
